# Generated by Django 6.0.8 on 2026-09-30 08:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_permission_codename_alter_role_name_and_more'),
        ('leave', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaveapproval',
            name='unique_leave_approval_level',
        ),
        migrations.RemoveConstraint(
            model_name='leavebalance',
            name='unique_employee_leave_balance',
        ),
        migrations.AddConstraint(
            model_name='leaveapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('leave_request', 'level'), name='unique_leave_approval_level'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'leave_type', 'year'), name='unique_employee_leave_balance'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(models.F('code'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_leavetype_code_alive'),
        ),
    ]
