# Generated by Django 6.0.8 on 2026-09-30 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_permission_uniq_permission_codename_alive_and_more'),
        ('leave', '0003_remove_leaveapproval_unique_leave_approval_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leaveapproval',
            name='unique_leave_approval_level',
        ),
        migrations.RemoveConstraint(
            model_name='leavebalance',
            name='unique_employee_leave_balance',
        ),
        migrations.RemoveConstraint(
            model_name='leavetype',
            name='uniq_leavetype_code_alive',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leavebalancetransaction',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leavepolicy',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='deleted_at',
        ),
        migrations.AddConstraint(
            model_name='leaveapproval',
            constraint=models.UniqueConstraint(fields=('leave_request', 'level'), name='unique_leave_approval_level'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_employee_leave_balance'),
        ),
        migrations.AddConstraint(
            model_name='leavetype',
            constraint=models.UniqueConstraint(models.F('code'), name='uniq_leavetype_code_alive'),
        ),
        migrations.RemoveField(
            model_name='leaveapproval',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='deleted_at',
        ),
    ]
