# Generated by Django 6.0.8 on 2026-09-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_remove_leaveapproval_unique_leave_approval_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalancetransaction',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='leavetype',
            name='uniq_leavetype_code_alive',
        ),
        migrations.AddField(
            model_name='leavebalancetransaction',
            name='leave_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_transactions', to='leave.leaverequest'),
        ),
    ]
