# Generated by Django 6.0.8 on 2026-09-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='codename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(models.F('codename'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_permission_codename_alive'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(models.F('name'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_role_name_alive'),
        ),
    ]
