# Generated by Django 6.0.8 on 2026-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_permission_codename_alter_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permission',
            name='uniq_permission_codename_alive',
        ),
        migrations.RemoveConstraint(
            model_name='role',
            name='uniq_role_name_alive',
        ),
        migrations.RemoveField(
            model_name='area',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='department',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='position',
            name='deleted_at',
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(models.F('codename'), name='uniq_permission_codename_alive'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(models.F('name'), name='uniq_role_name_alive'),
        ),
        migrations.RemoveField(
            model_name='permission',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='role',
            name='deleted_at',
        ),
    ]
