# Generated by Django 6.0.8 on 2026-09-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_permission_uniq_permission_codename_alive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
