# Generated by Django 6.1 on 2026-08-11 17:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('auto_shift', models.BooleanField(default=False, help_text='Automatically determine the matching timetable.')),
                ('cycle_unit', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='week', max_length=10)),
                ('cycle_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_shift_code')],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('flexible', 'Flexible')], default='normal', max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('work_minutes', models.PositiveIntegerField(blank=True, help_text='Required working minutes for flexible timetable.', null=True)),
                ('work_type', models.CharField(choices=[('work', 'Work'), ('off', 'Day Off'), ('overtime', 'Overtime')], default='work', max_length=20)),
                ('workday', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('check_in_start', models.TimeField(blank=True, null=True)),
                ('check_in_end', models.TimeField(blank=True, null=True)),
                ('check_out_start', models.TimeField(blank=True, null=True)),
                ('check_out_end', models.TimeField(blank=True, null=True)),
                ('check_in_cross_days', models.PositiveSmallIntegerField(default=0)),
                ('check_out_cross_days', models.PositiveSmallIntegerField(default=0)),
                ('require_check_in', models.BooleanField(default=True)),
                ('require_check_out', models.BooleanField(default=True)),
                ('allow_late_in', models.BooleanField(default=False)),
                ('allow_early_out', models.BooleanField(default=False)),
                ('late_in_grace_minutes', models.PositiveIntegerField(default=0)),
                ('early_out_grace_minutes', models.PositiveIntegerField(default=0)),
                ('multiple_in_out', models.BooleanField(default=False)),
                ('day_change_time', models.TimeField(default='08:00', help_text='Punches before this time may belong to the previous attendance day.')),
                ('color', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('code',), name='unique_timetable_code')],
            },
        ),
        migrations.CreateModel(
            name='OvertimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=False)),
                ('minimum_minutes', models.PositiveIntegerField(default=0)),
                ('maximum_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('count_early_in', models.BooleanField(default=False)),
                ('count_late_out', models.BooleanField(default=False)),
                ('early_in_minimum_minutes', models.PositiveIntegerField(default=0)),
                ('late_out_minimum_minutes', models.PositiveIntegerField(default=0)),
                ('timetable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_rule', to='schedule.timetable')),
            ],
            options={
                'verbose_name': 'Overtime rule',
                'verbose_name_plural': 'Overtime rules',
            },
        ),
        migrations.CreateModel(
            name='TimetableBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('paid', models.BooleanField(default=False)),
                ('minimum_minutes', models.PositiveIntegerField(default=0)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='schedule.timetable')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assignment_type', models.CharField(choices=[('employee', 'Employee'), ('department', 'Department'), ('group', 'Group')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('overwrite_existing', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='employees.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_assignments', to='employees.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='schedule.shift')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'start_date', 'end_date'], name='schedule_sc_employe_a34acf_idx'), models.Index(fields=['start_date', 'end_date'], name='schedule_sc_start_d_1e0822_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemporarySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('overrides_normal_schedule', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_schedules', to='employees.employee')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporary_schedules', to='schedule.timetable')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='schedule_te_employe_764aad_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date', 'timetable'), name='unique_employee_temp_schedule')],
            },
        ),
        migrations.CreateModel(
            name='ShiftDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day_number', models.PositiveIntegerField(help_text='Position inside the cycle, starting at 1.', validators=[django.core.validators.MinValueValidator(1)])),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedule.shift')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_days', to='schedule.timetable')),
            ],
            options={
                'ordering': ['day_number'],
                'constraints': [models.UniqueConstraint(fields=('shift', 'day_number'), name='unique_shift_day')],
            },
        ),
    ]
