# Generated by Django 6.0.8 on 2026-09-23 10:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(choices=[('normal', 'Normal'), ('flexible', 'Flexible')], default='normal', max_length=20)),
                ('check_out_cross_days', models.PositiveBigIntegerField(default=0)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('day_change_time', models.TimeField(default=datetime.time(8, 0), help_text='Punches before this time may belong to the previous attendance day.')),
                ('work_minutes', models.PositiveIntegerField(blank=True, help_text='Required working minutes for flexible timetable.', null=True)),
                ('check_in_start', models.TimeField(blank=True, null=True)),
                ('check_in_end', models.TimeField(blank=True, null=True)),
                ('grace_period_check_out', models.BooleanField(default=False)),
                ('grace_period_minutes', models.PositiveIntegerField(default=0)),
                ('count_break_time_as_work_time', models.BooleanField(default=False)),
                ('multiple_in_out', models.BooleanField(default=False)),
                ('duplicate_punch_window_minutes', models.PositiveIntegerField(default=1, help_text='Punches within this many minutes of the previous punch are treated as duplicates.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='Repeat anchor. Null = always active within the assignment range.', null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('repeat', models.BooleanField(default=True)),
                ('repeat_every', models.PositiveIntegerField(default=1)),
                ('repeat_unit', models.CharField(choices=[('week', 'Week'), ('month', 'Month'), ('year', 'Year')], default='week', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.timetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('break_time_type', models.CharField(choices=[('fixed', 'Fixed'), ('flexible', 'Flexible')], default='fixed', max_length=10)),
                ('break_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('grace_period_check_out', models.BooleanField(default=False)),
                ('grace_period_minutes', models.PositiveIntegerField(default=0)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='schedule.timetable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('is_day_off', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to='employees.employee')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='schedule.schedule')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['employee', 'date'], name='schedule_em_employe_292985_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_schedule_override')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Null = open-ended.', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher wins when assignments overlap on the same day.')),
                ('is_active', models.BooleanField(default=True)),
                ('employees', models.ManyToManyField(related_name='schedule_assignments', to='employees.employee')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='schedule.schedule')),
            ],
            options={
                'ordering': ['-priority', '-start_date'],
                'indexes': [models.Index(fields=['schedule', 'start_date'], name='schedule_em_schedul_7a2194_idx'), models.Index(fields=['start_date', 'end_date'], name='schedule_em_start_d_a55973_idx')],
            },
        ),
    ]
