# Generated by Django 6.0.8 on 2026-09-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_permission_codename_alter_role_name_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeescheduleoverride',
            name='unique_employee_schedule_override',
        ),
        migrations.RemoveIndex(
            model_name='employeescheduleoverride',
            name='schedule_em_employe_292985_idx',
        ),
        migrations.AddIndex(
            model_name='employeescheduleoverride',
            index=models.Index(fields=['date'], name='sched_override_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeescheduleoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('employee', 'date'), name='unique_employee_schedule_override'),
        ),
    ]
