# Generated by Django 6.0.8 on 2026-09-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_employeescheduleoverride_unique_employee_schedule_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='check_in_end',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='check_in_start',
        ),
        migrations.RemoveField(
            model_name='timetablebreak',
            name='grace_period_check_out',
        ),
        migrations.RemoveField(
            model_name='timetablebreak',
            name='grace_period_minutes',
        ),
    ]
