# Generated by Django 6.0.8 on 2026-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_permission_uniq_permission_codename_alive_and_more'),
        ('schedule', '0003_remove_timetable_check_in_end_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='employeescheduleoverride',
            name='unique_employee_schedule_override',
        ),
        migrations.RemoveField(
            model_name='employeescheduleassignment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='timetablebreak',
            name='deleted_at',
        ),
        migrations.AddConstraint(
            model_name='employeescheduleoverride',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_schedule_override'),
        ),
        migrations.RemoveField(
            model_name='employeescheduleoverride',
            name='deleted_at',
        ),
    ]
