# Generated by Django 6.0.8 on 2026-09-30 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_employeescheduleoverride_unique_employee_schedule_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day_change_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Punches before this time may belong to the previous attendance day.'),
        ),
    ]
