# Generated by Django 6.1 on 2026-08-18 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-id']},
        ),
    ]
