# Generated by Django 6.0.8 on 2026-09-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(models.F('serial_number'), condition=models.Q(('deleted_at__isnull', True)), name='uniq_device_serial_number_alive'),
        ),
    ]
