# Generated by Django 6.0.8 on 2026-09-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_device_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='device',
            name='uniq_device_serial_number_alive',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='devicebrand',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='devicetype',
            name='deleted_at',
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(models.F('serial_number'), name='uniq_device_serial_number_alive'),
        ),
        migrations.RemoveField(
            model_name='device',
            name='deleted_at',
        ),
    ]
