from django.db import connection, migrations


def _has_column(*, cursor, table: str, column: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = %s
          AND column_name = %s
        """,
        [table, column],
    )
    return cursor.fetchone() is not None


def _has_table(*, cursor, table: str) -> bool:
    cursor.execute(
        """
        SELECT 1
        FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = %s
        """,
        [table],
    )
    return cursor.fetchone() is not None


def restore_tenant_schema(apps, schema_editor):
    """
    Re-create TenantMixin columns after the local DB applied (then dropped)
    notenants migrations 0005_remove_tenant_fields / 0006_move_tenant_tables_to_public.

    Migration state still has Domain and schema_name from 0001_initial, so this
    only repairs the database. Fresh installs already have these objects; this
    is a no-op there.
    """
    if connection.vendor != "postgresql":
        return

    with connection.cursor() as cursor:
        if not _has_column(
            cursor=cursor, table="companies_company", column="schema_name"
        ):
            cursor.execute(
                """
                ALTER TABLE companies_company
                ADD COLUMN schema_name varchar(63) NULL
                """
            )

        cursor.execute("SELECT id FROM companies_company ORDER BY id")
        company_ids = [row[0] for row in cursor.fetchall()]

        for index, company_id in enumerate(company_ids):
            schema_name = "public" if index == 0 else f"company_{company_id}"
            cursor.execute(
                """
                UPDATE companies_company
                SET schema_name = %s
                WHERE id = %s AND (schema_name IS NULL OR schema_name = '')
                """,
                [schema_name, company_id],
            )
            if schema_name != "public":
                cursor.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema_name}"')

        cursor.execute(
            """
            SELECT 1
            FROM companies_company
            WHERE schema_name IS NULL
            LIMIT 1
            """
        )
        if cursor.fetchone() is None:
            cursor.execute(
                "ALTER TABLE companies_company ALTER COLUMN schema_name SET NOT NULL"
            )

        cursor.execute(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS companies_company_schema_name_key
            ON companies_company (schema_name)
            """
        )

        if not _has_table(cursor=cursor, table="companies_domain"):
            cursor.execute(
                """
                CREATE TABLE companies_domain (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    domain varchar(253) NOT NULL,
                    is_primary boolean NOT NULL DEFAULT true,
                    tenant_id bigint NOT NULL
                        REFERENCES companies_company (id) ON DELETE CASCADE
                )
                """
            )
            cursor.execute(
                """
                CREATE UNIQUE INDEX companies_domain_domain_key
                ON companies_domain (domain)
                """
            )
            cursor.execute(
                """
                CREATE INDEX companies_domain_is_primary_idx
                ON companies_domain (is_primary)
                """
            )
            cursor.execute(
                """
                CREATE INDEX companies_domain_tenant_id_idx
                ON companies_domain (tenant_id)
                """
            )

        cursor.execute(
            """
            SELECT id FROM companies_company
            WHERE schema_name = 'public'
            ORDER BY id
            LIMIT 1
            """
        )
        public_row = cursor.fetchone()
        if public_row is None:
            return

        public_id = public_row[0]
        for domain, is_primary in (("localhost", True), ("127.0.0.1", False)):
            cursor.execute(
                "SELECT 1 FROM companies_domain WHERE domain = %s",
                [domain],
            )
            if cursor.fetchone() is None:
                cursor.execute(
                    """
                    INSERT INTO companies_domain (domain, is_primary, tenant_id)
                    VALUES (%s, %s, %s)
                    """,
                    [domain, is_primary, public_id],
                )


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_devicebrand_devicetype_device"),
    ]

    operations = [
        migrations.RunPython(restore_tenant_schema, migrations.RunPython.noop),
    ]
