# Generated by Django 6.0.8 on 2026-09-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('over_time', models.DurationField(blank=True, null=True)),
                ('day', models.DateField()),
                ('total_work_time', models.DurationField(blank=True, null=True)),
                ('late_time', models.DurationField(blank=True, null=True)),
                ('early_leave_time', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early_out', 'Early Out'), ('incomplete', 'Incomplete'), ('day_off', 'Day Off'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='present', max_length=20)),
                ('is_calculated', models.BooleanField(default=False)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('punch_time', models.DateTimeField()),
                ('direction', models.CharField(choices=[('in', 'Check In'), ('out', 'Check Out'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('method', models.CharField(choices=[('biometric', 'Biometric'), ('web', 'Web'), ('mobile', 'Mobile'), ('manual', 'Manual')], default='biometric', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
