# Generated by Django 6.0.8 on 2026-09-01 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("employees", "0001_initial"),
        ("schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancecorrection",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_corrections_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_corrections",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendancecorrection",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_corrections_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancetransaction",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_transactions",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="check_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="check_in_periods",
                to="attendance.attendancetransaction",
            ),
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="check_out",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="check_out_periods",
                to="attendance.attendancetransaction",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="daily_attendance",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_results",
                to="schedule.shift",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="timetable",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_results",
                to="schedule.timetable",
            ),
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="daily_attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="periods",
                to="attendance.dailyattendance",
            ),
        ),
        migrations.AddField(
            model_name="overtimerecord",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overtime_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="overtimerecord",
            name="daily_attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overtime_records",
                to="attendance.dailyattendance",
            ),
        ),
        migrations.AddField(
            model_name="overtimerecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="overtime_records",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="overtimerecord",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overtime_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="attendancetransaction",
            index=models.Index(
                fields=["employee", "timestamp"], name="attendance__employe_38c499_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["employee", "date"], name="attendance__employe_0ead4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_a41095_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyattendance",
            constraint=models.UniqueConstraint(
                fields=("employee", "date"), name="unique_employee_attendance_day"
            ),
        ),
    ]
