# Generated by Django 6.0.8 on 2026-09-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceactivity',
            name='is_attendance_processed',
            field=models.BooleanField(default=False, help_text='True once this punch is consumed by attendance calculation or entered as a manual correction.'),
        ),
    ]
