# Generated by Django 6.0.8 on 2026-09-29 12:43

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill(apps, schema_editor):
    """Copy M2M punch links onto the new FK and persist day boundaries.

    Must run while ``attendance_activities`` still exists: the old model
    kept punch linkage in the M2M and computed ``first_in``/``last_out``
    by re-pairing punches on every read. New model stores both.
    """
    from attendance.calculation import dedupe_punches, pair_punches, summarize_pairs

    Attendance = apps.get_model("attendance", "Attendance")
    AttendanceActivity = apps.get_model("attendance", "AttendanceActivity")
    Through = apps.get_model("attendance", "Attendance_attendance_activities")
    TimetableBreak = apps.get_model("schedule", "TimetableBreak")

    links = {}
    for attendance_id, activity_id in Through.objects.values_list(
        "attendance_id", "attendanceactivity_id"
    ):
        links.setdefault(attendance_id, []).append(activity_id)

    break_cache = {}

    def breaks_for(timetable_id):
        if timetable_id not in break_cache:
            break_cache[timetable_id] = [
                (b.start_time, b.end_time)
                for b in TimetableBreak.objects.filter(timetable_id=timetable_id)
            ]
        return break_cache[timetable_id]

    rows = list(Attendance.objects.select_related("shift").order_by("pk"))
    for row in rows:
        punch_ids = links.get(row.pk, [])
        # Mirror the old read path: the M2M manager excluded
        # soft-deleted punches.
        punches = list(
            AttendanceActivity.objects.filter(
                pk__in=punch_ids, deleted_at__isnull=True
            ).order_by("punch_time", "id")
        )
        shift = row.shift
        summary = summarize_pairs(
            pair_punches(
                dedupe_punches(
                    punches,
                    window_minutes=(
                        shift.duplicate_punch_window_minutes if shift else 1
                    ),
                ),
                allow_multiple_in_out=bool(shift and shift.multiple_in_out),
                break_windows=breaks_for(row.shift_id) if shift else [],
            )
        )
        # Durations become NOT NULL; coerce what was NULL before the
        # AlterField operations (don't rely on backend-specific backfill).
        #
        # Everything must go through this single statement: PostgreSQL
        # leaves a pending trigger event when a row is updated twice in
        # one transaction, which makes the AlterField ALTERs below fail
        # with "cannot ALTER TABLE ... because it has pending trigger
        # events".
        payload = {
            "check_in": summary.first_in,
            "check_out": summary.last_out,
        }
        for field in ("total_work_time", "over_time", "late_time", "early_leave_time"):
            if getattr(row, field) is None:
                payload[field] = datetime.timedelta(0)
        Attendance.objects.filter(pk=row.pk).update(**payload)


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendanceactivity_is_attendance_processed'),
        ('employees', '0003_alter_employee_options'),
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_employee_attendance_day',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__employe_a13881_idx',
        ),
        migrations.RemoveField(
            model_name='attendanceactivity',
            name='is_attendance_processed',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='edit_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attendance',
            name='edited_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceactivity',
            name='attendance',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='activities',
                to='attendance.attendance',
            ),
        ),
        migrations.RunPython(_backfill, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='attendance',
            name='early_leave_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='late_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='over_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='total_work_time',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(
                choices=[
                    ('present', 'Present'),
                    ('absent', 'Absent'),
                    ('late', 'Late'),
                    ('early_out', 'Early Out'),
                    ('incomplete', 'Incomplete'),
                    ('day_off', 'Day Off'),
                    ('leave', 'Leave'),
                    ('holiday', 'Holiday'),
                ],
                default='incomplete',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='attendanceactivity',
            name='method',
            field=models.CharField(
                choices=[
                    ('biometric', 'Biometric'),
                    ('web', 'Web'),
                    ('mobile', 'Mobile'),
                    ('manual', 'Manual'),
                    ('correction', 'Correction'),
                ],
                default='biometric',
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(
                fields=['day', 'status'], name='att_day_status_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='attendanceactivity',
            index=models.Index(
                fields=['employee', 'punch_time'], name='act_emp_punch_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='attendanceactivity',
            index=models.Index(fields=['punch_time'], name='act_punch_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(
                condition=models.Q(('deleted_at__isnull', True)),
                fields=('employee', 'day'),
                name='unique_employee_attendance_day',
            ),
        ),
        migrations.AddConstraint(
            model_name='attendanceactivity',
            constraint=models.UniqueConstraint(
                condition=models.Q(('external_id', ''), _negated=True),
                fields=('external_id',),
                name='uniq_attendanceactivity_external_id',
            ),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_activities',
        ),
    ]
