# Generated by Django 6.0.8 on 2026-09-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendance_unique_employee_attendance_day_and_more'),
        ('employees', '0004_alter_permission_codename_alter_role_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendanceactivity',
            name='uniq_attendanceactivity_external_id',
        ),
        migrations.AddConstraint(
            model_name='attendanceactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), models.Q(('external_id', ''), _negated=True)), fields=('external_id',), name='uniq_attendanceactivity_external_id'),
        ),
    ]
