# Generated by Django 6.0.8 on 2026-09-30 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendanceactivity_uniq_attendanceactivity_external_id_and_more'),
        ('employees', '0005_remove_permission_uniq_permission_codename_alive_and_more'),
        ('schedule', '0004_remove_employeescheduleoverride_unique_employee_schedule_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_employee_attendance_day',
        ),
        migrations.RemoveConstraint(
            model_name='attendanceactivity',
            name='uniq_attendanceactivity_external_id',
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'day'), name='unique_employee_attendance_day'),
        ),
        migrations.AddConstraint(
            model_name='attendanceactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='uniq_attendanceactivity_external_id'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='attendanceactivity',
            name='deleted_at',
        ),
    ]
